config/routes.rb
Rails.application.routes.draw do
  resources 'users', only: :index do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end

  resources :projects do
    resources :messages, only: [:index, :create]
    resources :tasks, only: [:index, :create] do
      post 'complete', to: 'tasks#complete'
    end
  end
  devise_for :users,
    controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      registrations: "users/registrations",
    },
    path_names: {
      sign_in: 'sign-in', sign_out: 'sign-out',
      password: 'password', registration: '', sign_up: 'sign-up'
    }
  telegram_webhook TelegramWebhooksController

  root to: "home#index"
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  slug       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_projects_on_slug  (slug)
#
class Project < ApplicationRecord
  has_prefix_id :p
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
  normalizy :name

  # Associations
  has_many :messages, dependent: :destroy
  has_many :tasks, dependent: :destroy


  validates_uniqueness_of :name, case_sensitive: false

  private

  def should_generate_new_friendly_id?
    slug.blank? || self.name_changed?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  authorize_resource
  respond_to :html, :json

  def index
    @projects = Project.all
    respond_with(@projects)

  end

  def show
    respond_with(@project)
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    flash[:notice] = 'Project was successfully created.' if @project.save
    respond_with(@project)
  end

  def update
    flash[:notice] = 'Project was successfully updated.' if @project.update(project_params)
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name)
    end
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %>
        prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_list.erb
<%= turbo_frame_tag "projects-list"   do %>
  <div class="container-fluid scaffold-list">
    <h4>PROJECTS</h4>

    <%= render partial: "projects/new_button", locals: {}%><br/>

    <div class="row scaffold-heading-row"></div>
    <% if @project.present? %>
      <h5><%= @project.name %></h5>
      <div class=" scaffold-line-buttons  col-md-2">
        <%= form_with url: project_path(@project), html: {data: {'turbo-confirm': "Are you sure you want to delete #{ @project.name }?"}, style: "display: inline-block;"}, method: :delete do |f| %>
          <%= f.submit "Delete".html_safe,  class: "delete-project-button btn btn-danger btn-sm" %>
        <% end %>
        <%= link_to "Edit <i class='fa fa-1x fa-list-alt'></i>".html_safe, edit_project_path(@project), 'data-turbo' => 'false', disable_with: "Loading...", class: "edit-project-button btn btn-primary btn-sm" %>
      </div>
      <% @project.messages.order(created_at: :desc).each do |message| %>
        <p><%= message.content  %></p>
        <p><%= message.author  %></p>
      <% end %>

      <%= render 'messages/form' %>

    <% else %>
      <% @projects.each do |project| %>
        <%= render partial: 'projects/line', locals: {project: project } %>

      <% end %>

    <% end %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%=  link_to 'Messages', project_messages_path(project), class: "nav-link #{'active' if controller_name == 'messages' || controller_name == 'projects'}" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Tasks', project_tasks_path(project), class: "nav-link #{'active' if controller_name == 'tasks'}" %>
    </li>
  </ul>

  <%= turbo_stream_from project %>
  <% if controller_name == 'tasks' %>
    <%= render 'tasks/form' %>
    <div id="tasks">
      <%= render @tasks %>
    </div>

  <% else %>
    <%= render 'messages/form' %>
    <div id="messages">
      <%= render @project.messages.order(created_at: :desc) %>
    </div>
  <% end %>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <p>
      <%= link_to project.name, project %>
    </p>
  <% end %>
</div>

<% if can? :create, Project %>
  <%= link_to "New project", new_project_path, class: 'btn btn-primary' %>
<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<%= link_to "<< Back to projects", projects_path %>
<div class='float-end'>

  <% if can? :update, @project %>
    <%= link_to edit_project_path(@project), class: 'btn btn-primary' do %>

      <i class="fad fa-edit fa-lg"></i>
    <% end %>
  <% end %>

  <% if can? :destroy, @project %>
    <a href="#" alt="Delete <%= @project.name %>" data-controller="confirmable" data-action="confirmable#click" data-confirmable-title-value="Delete this Project?" data-confirmable-message-value="<p>Are you sure you want to delete the project &quot;<%= @project.name %>&quot;?<p>" data-confirmable-ok-button-value="Delete Project" data-confirmable-url-value="<%= project_path(@project) %>" data-confirmable-method-value="delete" class="btn btn-danger">
      <i class="fad fa-lg fa-trash"></i>
    </a>
  <% end %>
</div>
<h1>
  <strong><%= @project.name %></strong>
</h1>


<%= render @project %>