config/routes.rb
Rails.application.routes.draw do
  resources 'users', only: :index do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end

  resources :projects do
    resources :messages, only: [:index, :create]
    resources :tasks, only: [:index, :create] do
      post 'complete', to: 'tasks#complete'
    end
  end
  devise_for :users,
    controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      registrations: "users/registrations",
    },
    path_names: {
      sign_in: 'sign-in', sign_out: 'sign-out',
      password: 'password', registration: '', sign_up: 'sign-up'
    }
  telegram_webhook TelegramWebhooksController

  root to: "home#index"
end

app/views/layouts/_flash_notices.erb
<%= turbo_frame_tag "flash_notices" do %>
  <% unless notice.nil? %>
    <div class="alert alert-notice alert-dismissible">
      <%= notice %>
    </div>
  <% end %>
  <% unless alert.nil? %>
    <div class="alert alert-danger alert-dismissible">
      <%= alert %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_flash_notices.html.erb
<%= turbo_frame_tag "flash_notices" do %>
  <% unless notice.nil? %>
    <div class="alert alert-notice alert-dismissible">
      <%= notice %>
    </div>
  <% end %>
  <% unless alert.nil? %>
    <div class="alert alert-danger alert-dismissible">
      <%= alert %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_pretender.html.erb
<% if current_user != true_user %>
  You (<%= true_user.name %>) are signed in as
  <%= current_user.name %>
  <%= button_to "Back to admin", stop_impersonating_users_path, method: :post, class: 'btn btn-secondary' %>
<% end %>

app/views/layouts/_project_list.html.erb
<% id, name, slug = project_list_array %>
<li class="w-100">
  <%= link_to project_path(slug), class: 'nav-link px-0' do %>

    <span class="d-none d-sm-inline"><%= name %></span>
    <span class="d-inline d-sm-none">#<%= name.first(2).upcase %></span>

  <% end %>
</li>

app/views/layouts/_sidebar.erb
<div id='sidebar' class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
  <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
    <%= link_to root_path, class: 'd-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none' do  %>

      <%= image_tag 'logo.png', class: 'fs-5 d-none d-sm-inline', height: '50px' %>

    <% end %>
    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
      <li class="nav-item">
        <a href="#" class="nav-link align-middle px-0">
          <i class="fad fa-house"></i>
          <span class="ms-1 d-none d-sm-inline">Home</span>
        </a>
      </li>
      <li>
        <%= link_to projects_path, class: 'nav-link px-0 align-middle', data: {'bd-toggle' => 'collapse'} do %>
          <i class="fad fa-tasks"></i>
          <span class="ms-1 d-none d-sm-inline">Projects</span>
        <% end %>
        <% if @projects.present? %>
          <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
            <% @projects.each_with_index do |project, index| %>
              <li class="w-100">
                <%= link_to project_path(project), class: 'nav-link px-0' do %>
                  <span class="d-none d-sm-inline"><%= project.name %></span>
                  <span class="d-inline d-none"><%= index %></span>
                <% end %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </li>

    </ul>
    <hr>
    <% if current_user %>
      <div class="dropdown pb-4">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
          <% if current_user.avatar.attached?  %>
            <%= image_tag current_user.avatar.variant(resize_to_limit: [60, 60]).processed, width: "30", height: "30", class: 'rounded-circle' %>
          <% end %>
          <span class="d-none d-sm-inline mx-1"><%= current_user.name %><br/><small><%= current_user.role %></small>
          </span>

        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
          <% if current_user.admin? %>
            <li>
              <%= link_to 'Team', users_path, class: 'dropdown-item' %>
            </li>
          <% end %>
          <li>
            <%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li>
            <%= link_to 'Sign Out', destroy_user_session_path, data: { "turbo-method": :delete }, class: 'dropdown-item' %>

          </li>
        </ul>
      </div>
    <% else  %>
      <%= link_to new_user_registration_path, class:'d-flex align-items-center text-white text-decoration-none' do %>
        <i class='fad fa-circle-user'></i>
        <span class="d-none d-sm-inline mx-1">Account</span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div id='sidebar' class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
  <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
    <%= link_to root_path, class: 'd-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none' do  %>
      <%= image_tag 'logo.png', class: 'fs-5 d-none d-sm-inline', height: '50px' %>
    <% end %>
    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
      <li class="nav-item">
        <a href="/" class="nav-link align-middle px-0">
          <i class="fad fa-house"></i>
          <span class="ms-1 d-none d-sm-inline">Home</span>
        </a>
      </li>
      <% if can? :manage, User %>
        <li>
          <%= link_to users_path, class: 'nav-link px-0 align-middle' do %>
            <i class="fad fa-users"></i>
            <span class="ms-1 d-none d-sm-inline">Team</span>
          <% end %>
        </li>
      <% end %>
      <li>
        <%= link_to projects_path, class: 'nav-link px-0 align-middle', data: {'bd-toggle' => 'collapse'} do %>
          <i class="fad fa-tasks"></i>
          <span class="ms-1 d-none d-sm-inline">Projects</span>
        <% end %>


        <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
          <%= render(partial: 'layouts/project_list', collection: find_projects, as: :project_list_array, cached: true) %>

        </ul>
      </li>

    </ul>
    <hr>
    <% if current_user %>
      <div class="dropdown pb-4">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
          <% if current_user.avatar.attached?  %>
            <%= image_tag current_user.avatar.variant(resize_to_limit: [60, 60]).processed, width: "30", height: "30", class: 'rounded-circle' %>
          <% end %>
          <span class="d-none d-sm-inline mx-1"><%= current_user.name %><br/><small><%= current_user.role %></small>
          </span>

        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
          <% if can? :manage, User %>
            <li>
              <%= link_to 'Team', users_path, class: 'dropdown-item' %>
            </li>
          <% end %>
          <li>
            <%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, data: { "turbo-method": :delete }, class: 'dropdown-item' %>

          </li>
        </ul>
      </div>
    <% else  %>
      <%= link_to new_user_registration_path, class:'d-flex align-items-center text-white text-decoration-none' do %>
        <i class='fad fa-circle-user'></i>
        <span class="d-none d-sm-inline mx-1">Account</span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamWip</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://kit.fontawesome.com/6a4b034cbc.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row flex-nowrap">
        <%= render 'layouts/sidebar' %>

        <div class="col py-3">
          <%= render partial: 'layouts/pretender' %>
          <%= render partial: 'layouts/flash_notices' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>